[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:prometheus]
command=/opt/prometheus/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus --web.listen-address=:9090
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/prometheus.log
stderr_logfile=/var/log/supervisor/prometheus_err.log

[program:grafana]
command=/opt/grafana/bin/grafana-server --homepath=/opt/grafana --config=/opt/grafana/conf/defaults.ini
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/grafana.log
stderr_logfile=/var/log/supervisor/grafana_err.log
environment=GF_PATHS_DATA="/var/lib/grafana",GF_PATHS_LOGS="/var/log/grafana",GF_PATHS_PROVISIONING="/etc/grafana/provisioning",GF_SERVER_HTTP_PORT="3001"
user=root
